
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town01
#     num_zombie_vehicles: [30, 60]
#     num_zombie_walkers: [10, 30]
#     weather_group: train
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town02
#     num_zombie_vehicles: [40, 50]
#     num_zombie_walkers: [30, 40]
#     weather_group: train
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town03
#     num_zombie_vehicles: [70, 80]
#     num_zombie_walkers: [40, 50]
#     weather_group: train
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town04
#     num_zombie_vehicles: [130, 140]
#     num_zombie_walkers: [80,90]
#     weather_group: train
#   gpu: [1]
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town05
#     num_zombie_vehicles: [100, 110]
#     num_zombie_walkers: [0, 1]
#     weather_group: train
- env_id: SimpleRoute-v0
  env_configs:
    carla_map: Town03
    routes_group: null
    weather_group: train
  gpu: [1]