
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town01
#     num_zombie_vehicles: [40, 50]
#     num_zombie_walkers: [20, 30]
#     weather_group: dynamic_1.0
#   gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town02
    num_zombie_vehicles: [70, 80]
    num_zombie_walkers: [40, 50]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town03
    num_zombie_vehicles: [80, 90]
    num_zombie_walkers: [40, 50]
    weather_group: dynamic_1.0
  gpu: [0]
- env_id: Endless-v0
  env_configs:
    carla_map: Town04
    num_zombie_vehicles: [80, 90]
    num_zombie_walkers: [30, 40]
    weather_group: dynamic_1.0
  gpu: [0]
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town05
#     num_zombie_vehicles: [0, 160]
#     num_zombie_walkers: [0, 160]
#     weather_group: dynamic_1.0
#   gpu: [0]
# - env_id: Endless-v0
#   env_configs:
#     carla_map: Town06
#     num_zombie_vehicles: [0, 160]
#     num_zombie_walkers: [0, 160]
#     weather_group: dynamic_1.0
#   gpu: [0]
